/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function magikSync(buffer: Uint8Array): Uint8ClampedArray
export class Magik {
  constructor(input: Uint8Array)
  magikify(signal?: AbortSignal | undefined | null): Promise<Uint8ClampedArray>
}
